# Generated by Django 5.2 on 2025-04-28 05:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_viewer_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SheetImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anchor', models.CharField(max_length=50)),
                ('image_file', models.ImageField(upload_to='sheet_images/')),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='excel_viewer_app.sheet')),
            ],
        ),
    ]
