# Generated by Django 5.2 on 2025-04-28 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_viewer_app', '0002_sheetimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheet',
            name='column_widths',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='sheet',
            name='images',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='sheet',
            name='merged_cells',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='sheet',
            name='row_heights',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.DeleteModel(
            name='SheetImage',
        ),
    ]
