# Generated by Django 5.2 on 2025-04-28 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_viewer_app', '0003_sheet_column_widths_sheet_images_sheet_merged_cells_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sheet',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
