# Generated by Django 5.2 on 2025-04-28 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_viewer_app', '0004_alter_sheet_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sheet',
            name='column_widths',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='excel_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='excel_viewer_app.excelfile'),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='images',
            field=models.FileField(blank=True, null=True, upload_to='sheet_images/'),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='merged_cells',
            field=models.TextField(default='[]'),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='row_heights',
            field=models.JSONField(default=dict),
        ),
    ]
