# Generated by Django 5.2 on 2025-04-28 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_viewer_app', '0005_alter_sheet_column_widths_alter_sheet_excel_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='sheet_images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='sheet',
            name='images',
        ),
        migrations.AddField(
            model_name='sheet',
            name='images',
            field=models.ManyToManyField(blank=True, to='excel_viewer_app.image'),
        ),
    ]
