# Generated by Django 5.2 on 2025-04-28 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_viewer_app', '0006_image_remove_sheet_images_sheet_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='file',
        ),
        migrations.AddField(
            model_name='image',
            name='image',
            field=models.ImageField(default=None, upload_to='images/'),
            preserve_default=False,
        ),
    ]
