# Generated by Django 5.2 on 2025-04-28 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('excel_viewer_app', '0007_remove_image_file_image_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='uploaded_at',
            new_name='created_at',
        ),
    ]
