# Generated by Django 5.2 on 2025-05-02 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_viewer_app', '0008_rename_uploaded_at_image_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='column',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='row',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
