# Generated by Django 5.2 on 2025-09-18 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_viewer_app', '0009_image_column_image_row'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sheet',
            name='images',
        ),
        migrations.AddField(
            model_name='image',
            name='sheet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='excel_viewer_app.sheet'),
        ),
    ]
