# Generated by Django 5.2 on 2025-09-18 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_viewer_app', '0010_remove_sheet_images_image_sheet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='sheet',
        ),
        migrations.AddField(
            model_name='sheet',
            name='images',
            field=models.ManyToManyField(blank=True, to='excel_viewer_app.image'),
        ),
    ]
