# Generated by Django 5.2 on 2025-09-21 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_viewer_app', '0011_remove_image_sheet_sheet_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheetentry',
            name='date_mapped',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
