# Generated by Django 5.2 on 2025-09-23 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_viewer_app', '0012_sheetentry_date_mapped'),
    ]

    operations = [
        migrations.AddField(
            model_name='excelfile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
