# Generated by Django 5.2 on 2025-09-24 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('excel_viewer_app', '0015_clientfile_sheet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientfile',
            name='sheet',
        ),
    ]
