# Generated by Django 5.2 on 2025-09-25 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_viewer_app', '0016_remove_clientfile_sheet'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientfile',
            name='sheet',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='excel_viewer_app.sheet'),
        ),
    ]
