# Generated by Django 5.2 on 2025-09-26 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_viewer_app', '0018_clientfile_excel_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='excelfile',
            name='pdf_tabs',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
