# Generated by Django 5.2 on 2025-10-01 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_viewer_app', '0019_excelfile_pdf_tabs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='excelfile',
            name='pdf_tabs',
        ),
        migrations.AddField(
            model_name='excelfile',
            name='pdf_full',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
