# Generated by Django 5.2 on 2025-10-02 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_viewer_app', '0020_remove_excelfile_pdf_tabs_excelfile_pdf_full'),
    ]

    operations = [
        migrations.AddField(
            model_name='excelfile',
            name='pdf_tabs',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
