# Generated by Django 5.2 on 2025-10-17 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('excel_viewer_app', '0021_excelfile_pdf_tabs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='excelfile',
            name='pdf_full',
        ),
    ]
