# Generated by Django 5.2 on 2025-10-17 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_viewer_app', '0022_remove_excelfile_pdf_full'),
    ]

    operations = [
        migrations.AddField(
            model_name='excelfile',
            name='pdf_full',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
